# This file could be generated, or the list of model libraries could be a command line flag. Let's start with the latter.
import os

# g++-mp-4.9 -std=c++11 -o gmcfCoupler -Wall -DWORDSZ=64 -DUSE_THREADS=1 -I$PWD/gensrc -I$GANNET_DIR/GPRM/src -I$GANNET_DIR/GPRM/src/SBA  -L$PWD/lib -L$PWD/src/GMCF/Models $GANNET_DIR/GPRM/src/gmcfCoupler.cc -lgmcf -lgmcfAPI -lgfortran -lmodel1 -lmodel2 
models=ARGUMENTS.get('models','model1,model2')
modellibs=models.split(',')

CXX=os.environ['CXX']
GANNET_DIR=os.environ['GANNET_DIR']
wd= os.environ['PWD']

gmcfsources=[ GANNET_DIR+'/GPRM/src/gmcfCoupler.cc']
LDFLAGS=['-pthread']
FFLAGS=['-std=c++11','-Wall', '-DWORDSZ=64', '-DUSE_THREADS=1']
CXXFLAGS=[ '-Wall',  '-std=c++11' ,  '-DWORDSZ=64', '-DUSE_THREADS=1']
INCPATHS=[ GANNET_DIR+'/GPRM/src', GANNET_DIR+'/GPRM/src/SBA',  wd+'/gensrc']
LIBPATHS=[wd+'/lib', wd+'/src/GMCF/Models']
LIBS=[ 'gmcf']+modellibs+['gmcfAPI', 'gmcf', 'gfortran']
env=Environment(LINK=CXX,LINKFLAGS=LDFLAGS,CXX=CXX,CXXFLAGS=CXXFLAGS,CPPPATH=INCPATHS,LIBPATH=LIBPATHS)
env.Program('gmcfCoupler',gmcfsources,LIBS=LIBS) 


